"""
replicate_figures.py — Regenerate data for manuscript figures.

Saves numerical outputs and PNG plots to figure_outputs/.
Figures 1 and 2 are schematics/spectra not generated by this code.

Usage:
    python replicate_figures.py              # all figures
    python replicate_figures.py --figure 3   # single figure

Reproduces, for the JBO HDR SWIR manuscript:
    Fig 3      dark-current + saturation calibration
    Fig 4a-d   CRF recovery for the four preprocessing variants
    Fig 4e-f   short-exposure CRF applied to longer exposures
    Fig 4g     CRF recovery under four weighting functions
    Fig 5      ICG dilution plate HDR radiance
    Fig 6      QD mouse HDR (default vs adaptive) + histograms
    Fig 7      NOT replicated (manual ROIs / line-profile coordinates)

CSV files are written alongside the PNGs for import into GraphPad Prism.
"""

import os
import sys
import glob
import argparse
import traceback
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit

REPO_ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(REPO_ROOT))

from config import load_config
import Step0_calibration as step0
import Step1_import as step1
import Step2_radiance as step2

OUT = REPO_ROOT / "figure_outputs"

# CRF recovery uses random pixel sampling; fix the seed so figures reproduce.
SEED = 0
SMOOTHING_LAMBDA = 1000

# Weighting functions available for CRF recovery. "debevec" is the calibration
# default (Step0._debevec); the others come from Step2.
WEIGHTS = {
    "debevec":   step0._debevec,
    "robertson": step2.robertson,
    "broadhat":  step2.broadhat,
    "vinegoni":  step2.vinegoni,
}


# --------------------------------------------------------------------------- #
#  Shared helpers
# --------------------------------------------------------------------------- #

def load_calibration(calib_dir):
    """Load Sd, b, Smax, crf calibration arrays."""
    Sd   = np.load(os.path.join(calib_dir, "Sd.npy"))
    b    = np.load(os.path.join(calib_dir, "b.npy"))
    Smax = np.load(os.path.join(calib_dir, "Smax.npy"))
    crf  = np.load(os.path.join(calib_dir, "crf.npy"))
    return Sd, b, Smax, crf


def preprocess_variant(images, exposure_times, Sd, b, Smax, variant):
    """
    Produce (processed_images, Zmax, Zmin) for one CRF preprocessing variant.

        a : raw (no preprocessing)
        b : clip to Smax
        c : denoise (subtract per-pixel dark current Sd*t + b)
        d : clip to Smax AND denoise  (the manuscript choice; matches
            run_calibration in Step0_calibration)
    """
    n = len(exposure_times)
    H, W = Smax.shape
    images = images.astype(np.float32)
    DC = np.stack([Sd * t + b for t in exposure_times]).astype(np.float32)
    Smax_b = np.broadcast_to(Smax, (n, H, W)).astype(np.float32)

    if variant == "a":
        proc = images
        zmax = np.full((n, H, W), float(images.max()), np.float32)
        zmin = np.zeros((n, H, W), np.float32)
    elif variant == "b":
        # Constrain to both bounds: clip sub-noise pixels up to DC(t) and
        # saturated pixels down to Smax. Zmin = DC(t) shifts the tent midpoint
        # upward so sub-noise pixels get zero weight.
        proc = np.clip(images, DC, Smax_b).astype(np.float32)
        zmax = Smax_b.copy()
        zmin = DC.copy()
    elif variant == "c":
        proc = np.maximum(images - DC, 0).astype(np.float32)
        zmax = np.full((n, H, W), float(proc.max()), np.float32)
        zmin = np.zeros((n, H, W), np.float32)
    elif variant == "d":
        proc = np.maximum(np.minimum(images, Smax_b) - DC, 0).astype(np.float32)
        zmax = (Smax_b - DC).astype(np.float32)
        zmin = np.zeros((n, H, W), np.float32)
    else:
        raise ValueError(f"unknown variant {variant!r}")

    return proc, zmax, zmin


def recover_crf(proc, times, zmax, zmin, weighting, seed=SEED):
    """Sample intensities and solve for the camera response function (two-step)."""
    np.random.seed(seed)
    isamp, logE, srad, zmn, zmx = step0.sampleIntensities(
        proc, times, zmax, zmin, weighting)
    crf = step0.computeResponseCurve(
        isamp, logE, times, SMOOTHING_LAMBDA, weighting,
        zmn, zmx, zmax, zmin)
    return crf, isamp, logE


def crf_fit_stats(crf, crf_min, isamp, log_exposures, times):
    """
    Goodness-of-fit of a recovered CRF g(z): how well g(z_ij) predicts the
    pre-estimated log-exposures ln(Ê_i × t_j) returned by sampleIntensities.

    Residual = log_exposures[i,j] - g(z_ij), where g(z_ij) = crf[z_ij - crf_min].
    Points with pixel intensity 0 (denoised background) are excluded from R^2.
    crf_min is the intensity value that maps to crf[0].
    """
    idx = np.clip(np.round(isamp - crf_min).astype(int), 0, len(crf) - 1)
    g = crf[idx]                                   # (N, P) g(z_ij)
    resid = log_exposures - g                      # (N, P)

    mask = isamp > 0                               # exclude zero-intensity pixels
    L = log_exposures[mask]
    r = resid[mask]
    ss_res = float(np.sum(r ** 2))
    ss_tot = float(np.sum((L - L.mean()) ** 2))
    r2 = 1.0 - ss_res / ss_tot if ss_tot > 0 else float("nan")

    N, P = isamp.shape
    return {
        "r2": r2,
        "n_samples": N,
        "n_used": int(mask.sum()),
        "crf_min": crf_min,
        "isamp": isamp,                # (N, P) for per-exposure coloring
        "logE": log_exposures,         # (N, P)
        "resid": resid,                # (N, P)
        "times": times,
        # flattened for CSV export
        "intensity": isamp.flatten(),
        "log_exposure": log_exposures.flatten(),
        "exposure_time": np.tile(times, N),
    }


def plot_crf_with_data(crf, stats, title, png_path):
    """
    Manuscript Fig 4 layout: pixel intensity on the x-axis (log scale),
    log-exposure ln(Ê·t) on the y-axis. Sampled points are colored by exposure
    time so the per-exposure fanning is visible; the recovered CRF g(z) is
    overlaid (x = pixel intensity index, y = g(z)). Residuals below.
    """
    crf_min = stats["crf_min"]
    z_dom = np.arange(crf_min, crf_min + len(crf))
    isamp, logE, resid, times = (stats["isamp"], stats["logE"],
                                 stats["resid"], stats["times"])
    colors = plt.get_cmap("viridis")(np.linspace(0, 1, len(times)))

    fig, (ax0, ax1) = plt.subplots(
        2, 1, figsize=(6, 6), sharex=True,
        gridspec_kw={"height_ratios": [3, 1]})

    for j, t in enumerate(times):
        ax0.scatter(isamp[:, j], logE[:, j], s=3, alpha=0.3,
                    color=colors[j], label=f"{t:.3f}s")
    ax0.plot(z_dom, crf, "k-", lw=2, label="recovered CRF g(z)")
    ax0.set_xscale("log")
    ax0.set_ylabel(r"$\ln(\hat{E}\cdot t)$  (ln exposure)")
    ax0.set_title(f"{title}   (R$^2$={stats['r2']:.4f}, n={stats['n_used']})")
    ax0.legend(loc="best", fontsize=7, ncol=2)

    for j in range(len(times)):
        ax1.scatter(isamp[:, j], resid[:, j], s=3, alpha=0.3, color=colors[j])
    ax1.axhline(0, color="k", lw=1)
    ax1.set_xscale("log")
    ax1.set_xlabel("pixel intensity (DN)")
    ax1.set_ylabel("residual\n(ln units)")

    fig.tight_layout()
    fig.savefig(png_path, dpi=200)
    plt.close(fig)


def save_csv(df, name):
    path = OUT / name
    df.to_csv(path, index=False)
    return path


def hist_centers_counts(data, bins):
    counts, edges = np.histogram(data, bins=bins)
    centers = 0.5 * (edges[:-1] + edges[1:])
    return centers, counts


def run_hdr(directory, experiment_title, base_data_folder, operations,
            params, crf, weighting_fn, method):
    """
    Step 1 (import+preprocess) then Step 2 (HDR fusion). process_hdr_images
    chdir's into the data folder, so we restore cwd afterwards.
    """
    step1.process_and_save(directory, experiment_title, base_data_folder,
                           operations=operations, params=params)
    cwd = os.getcwd()
    try:
        processed = step2.process_hdr_images(
            directory, experiment_title, base_data_folder,
            coefficients_dict=params, response_curve=crf,
            weighting_function=weighting_fn, method=method)
    finally:
        os.chdir(cwd)
    return processed


def load_processed_stack(directory, base_data_folder, key):
    """Load the preprocessed (clip_denoise) image stack saved by Step 1."""
    folder = os.path.join(directory, base_data_folder, "processed_data")
    matches = glob.glob(os.path.join(folder, f"{key}_*.npy"))
    if not matches:
        return None, None
    data = np.load(matches[0], allow_pickle=True)
    return data["image"], data["exposure_time"]


# --------------------------------------------------------------------------- #
#  Figure 3 — dark current + saturation
# --------------------------------------------------------------------------- #

def figure3(cfg):
    cal = cfg["calibration"]
    Sd, b, Smax, _ = load_calibration(cal["output_dir"])

    print(f"[Fig3] Sd   mean={Sd.mean():.4f}  std={Sd.std():.4f}  (DN/s)")
    print(f"[Fig3] b    mean={b.mean():.4f}  std={b.std():.4f}  (DN)")
    print(f"[Fig3] Smax mean={Smax.mean():.4f}  std={Smax.std():.4f}  (DN)")

    # Per-pixel histograms for Prism
    for arr, name in [(Sd, "Sd"), (b, "b")]:
        centers, counts = hist_centers_counts(arr.flatten(), bins=100)
        save_csv(pd.DataFrame({"bin_center": centers, "count": counts}),
                 f"fig3_{name}_histogram.csv")

    # --- Mean dark current vs exposure, with the linear DC model overlaid ---
    dc_arr, dc_times = step0.import_darkcount_data(cal["dc_dir"])
    dc_arr, dc_times = step0.sort_by_exposure_time(dc_arr, dc_times)
    mean_dc = step0.analyze_darkcount_data(dc_arr, dc_times)["mean"]
    model_dc = Sd.mean() * dc_times + b.mean()

    save_csv(pd.DataFrame({"exposure_time": dc_times, "mean_DC": mean_dc,
                           "model_DC": model_dc}),
             "fig3_dc_vs_exposure.csv")

    fig, ax = plt.subplots(figsize=(5, 4))
    ax.scatter(dc_times, mean_dc, color="k", label="measured mean DC")
    ax.plot(dc_times, model_dc, "r-",
            label=f"linear model  Sd·t + b\n(Sd={Sd.mean():.2f}, b={b.mean():.1f})")
    ax.set_xlabel("exposure time (s)")
    ax.set_ylabel("mean dark current (DN)")
    ax.set_title("Fig 3 — dark current vs exposure")
    ax.legend(fontsize=8)
    fig.tight_layout(); fig.savefig(OUT / "fig3_dc_vs_exposure.png", dpi=200)
    plt.close(fig)

    # --- Mean intensity vs exposure (log) with sensor-average sigmoid fit ---
    refl, refl_times = step0.import_reflectance_data(cal["reflectance_dir"])
    refl, refl_times = step0.sort_by_exposure_time(refl, refl_times)
    mean_int = refl.reshape(len(refl_times), -1).mean(axis=1)

    # Fit a single sigmoid to the spatially-averaged response ("sensor average").
    log_t = np.log10(refl_times)
    rng = mean_int.max() - mean_int.min()
    p0 = [rng, np.median(log_t), 0.5, mean_int.min()]
    bounds = ([0.1 * rng, log_t.min(), 0.1, mean_int.min()],
              [2.0 * rng, log_t.max(), 2.0, mean_int.max()])
    popt, _ = curve_fit(step0.sigmoid_curve, refl_times, mean_int,
                        p0=p0, bounds=bounds, maxfev=10000)
    a_, b_, c_, d_ = popt

    save_csv(pd.DataFrame({"exposure_time": refl_times, "mean_intensity": mean_int}),
             "fig3_intensity_vs_exposure.csv")
    save_csv(pd.DataFrame({"parameter": ["a", "b", "c", "d"], "value": popt}),
             "fig3_sigmoid_params.csv")
    print(f"[Fig3] sigmoid (sensor average): a={a_:.2f} b={b_:.3f} "
          f"c={c_:.3f} d={d_:.2f}")

    t_fine = np.logspace(np.log10(refl_times.min()), np.log10(refl_times.max()), 500)
    fig, ax = plt.subplots(figsize=(5, 4))
    ax.scatter(refl_times, mean_int, color="k", label="measured")
    ax.plot(t_fine, step0.sigmoid_curve(t_fine, *popt), "r-", label="sigmoid fit")
    ax.set_xscale("log")
    ax.set_xlabel("exposure time (s)")
    ax.set_ylabel("mean pixel intensity (DN)")
    ax.set_title("Fig 3 — saturation response")
    ax.legend(fontsize=8)
    fig.tight_layout(); fig.savefig(OUT / "fig3_intensity_vs_exposure.png", dpi=200)
    plt.close(fig)


# --------------------------------------------------------------------------- #
#  Figure 4a-d — CRF preprocessing variants
# --------------------------------------------------------------------------- #

def figure4ad(cfg):
    cal = cfg["calibration"]
    Sd, b, Smax, _ = load_calibration(cal["output_dir"])
    crf_dir = str(REPO_ROOT / "data/Images/CRFrecovery/checkerboard_short")

    images, times = step0.import_reflectance_data(crf_dir)
    images, times = step0.sort_by_exposure_time(images, times)
    print(f"[Fig4a-d] checkerboard_short: {len(times)} exposures "
          f"{times.min():.3f}-{times.max():.3f}s")

    crfs = {}
    rows = []
    for v in ["a", "b", "c", "d"]:
        proc, zmax, zmin = preprocess_variant(images, times, Sd, b, Smax, v)
        crf, isamp, logE = recover_crf(proc, times, zmax, zmin, step0._debevec)
        crf_min = int(np.min(isamp))
        stats = crf_fit_stats(crf, crf_min, isamp, logE, times)
        crfs[f"crf_{v}"] = crf
        rows.append({"variant": v, "r2": stats["r2"],
                     "n_samples": stats["n_samples"], "n_used": stats["n_used"],
                     "crf_len": len(crf)})
        print(f"[Fig4{v}] R2={stats['r2']:.4f}  n_used={stats['n_used']}  "
              f"crf_len={len(crf)}")

        save_csv(pd.DataFrame({
            "pixel_intensity": stats["intensity"],
            "log_exposure":    stats["log_exposure"],
            "exposure_time":   stats["exposure_time"],
        }), f"fig4{v}_samples.csv")

        plot_crf_with_data(crf, stats, f"Fig 4{v} (variant {v})",
                           OUT / f"fig4{v}_crf.png")

    save_csv(pd.DataFrame(rows), "fig4_r2_summary.csv")
    np.savez(OUT / "fig4_crfs.npz", **crfs)


# --------------------------------------------------------------------------- #
#  Figure 4e-f — short-exposure CRF applied to long exposures
# --------------------------------------------------------------------------- #

def figure4ef(cfg):
    cal = cfg["calibration"]
    # Use the calibration CRF (recovered from the short exposures); do NOT
    # recompute. It is indexed from intensity 0 (variant-d denoised data).
    Sd, b, Smax, crf_short = load_calibration(cal["output_dir"])

    # Prefer CRFrecovery_full (0.25-8 s subset) if present, else checkerboard_long.
    long_dir = REPO_ROOT / "data/Images/CRFrecovery_full"
    if not long_dir.exists():
        long_dir = REPO_ROOT / "data/Images/CRFrecovery/checkerboard_long"
    long_dir = str(long_dir)

    # Long exposures, variant (d), sampled the same way as the calibration.
    l_img, l_t = step0.import_reflectance_data(long_dir)
    l_img, l_t = step0.sort_by_exposure_time(l_img, l_t)
    l_proc, l_zmax, l_zmin = preprocess_variant(l_img, l_t, Sd, b, Smax, "d")
    np.random.seed(SEED)
    l_isamp, l_logE, _, _, _ = step0.sampleIntensities(
        l_proc, l_t, l_zmax, l_zmin, step0._debevec)
    print(f"[Fig4e-f] long exposures: {len(l_t)} "
          f"{l_t.min():.3f}-{l_t.max():.3f}s  ({long_dir})")

    # Apply the existing short-exposure CRF to the long-exposure samples.
    stats = crf_fit_stats(crf_short, 0, l_isamp, l_logE, l_t)
    print(f"[Fig4e-f] short-CRF on long samples: R2={stats['r2']:.4f}  "
          f"n_used={stats['n_used']}")

    save_csv(pd.DataFrame({
        "pixel_intensity": stats["intensity"],
        "log_exposure":    stats["log_exposure"],
        "exposure_time":   stats["exposure_time"],
    }), "fig4ef_long_samples.csv")
    save_csv(pd.DataFrame({"r2": [stats["r2"]],
                           "n_samples": [stats["n_samples"]],
                           "n_used": [stats["n_used"]]}),
             "fig4ef_r2.csv")

    plot_crf_with_data(crf_short, stats,
                       "Fig 4e-f — short CRF on long exposures",
                       OUT / "fig4ef_long_crf.png")


# --------------------------------------------------------------------------- #
#  Figure 4g — weighting functions
# --------------------------------------------------------------------------- #

def figure4g(cfg):
    cal = cfg["calibration"]
    Sd, b, Smax, _ = load_calibration(cal["output_dir"])
    crf_dir = str(REPO_ROOT / "data/Images/CRFrecovery/checkerboard_short")

    images, times = step0.import_reflectance_data(crf_dir)
    images, times = step0.sort_by_exposure_time(images, times)
    proc, zmax, zmin = preprocess_variant(images, times, Sd, b, Smax, "d")

    curves = {}   # name -> (z_domain, crf)
    saved = {}
    for name, wfn in WEIGHTS.items():
        crf, isamp, logE = recover_crf(proc, times, zmax, zmin, wfn)
        z0 = int(np.min(isamp))
        z_dom = np.arange(z0, z0 + len(crf))
        curves[name] = (z_dom, crf)
        saved[f"crf_{name}"] = crf
        saved[f"z_{name}"] = z_dom
        print(f"[Fig4g] {name}: crf_len={len(crf)}  "
              f"z=[{z_dom[0]}, {z_dom[-1]}]")

    np.savez(OUT / "fig4g_weighting_crfs.npz", **saved)

    # Max pairwise deviation on the common intensity domain.
    lo = max(z[0] for z, _ in curves.values())
    hi = min(z[-1] for z, _ in curves.values())
    z_common = np.arange(lo, hi + 1)
    interp = {n: np.interp(z_common, z, c) for n, (z, c) in curves.items()}
    names = list(interp)
    max_dev = 0.0
    for i in range(len(names)):
        for j in range(i + 1, len(names)):
            d = np.max(np.abs(interp[names[i]] - interp[names[j]]))
            max_dev = max(max_dev, d)
    print(f"[Fig4g] max pairwise CRF deviation (common domain) = {max_dev:.4f} ln units")

    df = pd.DataFrame({"pixel_intensity": z_common})
    for n in names:
        df[f"crf_{n}"] = interp[n]
    save_csv(df, "fig4g_weighting_crfs.csv")
    save_csv(pd.DataFrame({"max_pairwise_deviation_ln": [max_dev]}),
             "fig4g_max_deviation.csv")

    fig, ax = plt.subplots(figsize=(5, 4))
    for n, (z, c) in curves.items():
        ax.plot(z, c, lw=1.5, label=n)
    ax.set_xlabel("pixel intensity (DN)")
    ax.set_ylabel("g(z)  (ln exposure)")
    ax.set_title(f"Fig 4g — weighting functions\n(max dev {max_dev:.3f} ln units)")
    ax.legend(fontsize=8)
    fig.tight_layout(); fig.savefig(OUT / "fig4g_weighting_overlay.png", dpi=200)
    plt.close(fig)


# --------------------------------------------------------------------------- #
#  Figure 5 — ICG dilution plate
# --------------------------------------------------------------------------- #

def figure5(cfg):
    cal = cfg["calibration"]
    imp = cfg["import"]
    Sd, b, Smax, crf = load_calibration(cal["output_dir"])
    params = {"Sd": Sd, "b": b, "Smax": Smax}

    directory = str(REPO_ROOT / "data/Images/ICG_images/ICGplate3")
    experiment_title = "ICGplate3"
    # Write pipeline output under figure_outputs/ (absolute path) so the tracked
    # data/Images tree isn't polluted with large generated HDR_data files.
    base = str(OUT / f"{experiment_title}_HDR_data")

    processed = run_hdr(directory, experiment_title, base,
                        imp["preprocessing_ops"], params, crf,
                        step2.debevec, method="default")
    if not processed:
        raise RuntimeError("no ICG radiance map produced")

    rad_log = processed[0]["radiance_map"]      # log radiance
    rad_lin = np.exp(rad_log)
    np.save(OUT / "fig5_ICG_radiance.npy", rad_lin.astype(np.float32))

    pos = rad_lin[np.isfinite(rad_lin) & (rad_lin > 0)]
    dr_ratio = float(pos.max() / pos.min())
    dr_db = 20.0 * np.log10(dr_ratio)
    # Robust dynamic range over 1st-99th percentile signal.
    p1, p99 = np.percentile(pos, [1, 99])
    dr_db_robust = 20.0 * np.log10(p99 / p1)
    print(f"[Fig5] scene dynamic range: {dr_ratio:.3e}x  ({dr_db:.1f} dB full, "
          f"{dr_db_robust:.1f} dB 1-99 pct)")
    save_csv(pd.DataFrame({
        "metric": ["max", "min", "dr_ratio", "dr_dB", "dr_dB_1_99pct"],
        "value": [pos.max(), pos.min(), dr_ratio, dr_db, dr_db_robust]}),
        "fig5_dynamic_range.csv")

    fig, ax = plt.subplots(figsize=(6, 5))
    disp = np.log10(np.where(rad_lin > 0, rad_lin, np.nan))
    im = ax.imshow(disp, cmap="viridis")
    ax.set_title("Fig 5 — ICG plate HDR radiance (log10)")
    ax.axis("off")
    fig.colorbar(im, ax=ax, label="log10 radiance (a.u.)")
    fig.tight_layout(); fig.savefig(OUT / "fig5_ICG_radiance.png", dpi=200)
    plt.close(fig)


# --------------------------------------------------------------------------- #
#  Figure 6 — QD mouse HDR (default vs adaptive)
# --------------------------------------------------------------------------- #

def _save_radiance_png(rad_log, title, path, log=True):
    fig, ax = plt.subplots(figsize=(6, 5))
    if log:
        disp = np.log10(np.where(np.exp(rad_log) > 0, np.exp(rad_log), np.nan))
        label = "log10 radiance (a.u.)"
    else:
        disp = np.exp(rad_log)
        label = "radiance (a.u.)"
    im = ax.imshow(disp, cmap="gray")
    ax.set_title(title); ax.axis("off")
    fig.colorbar(im, ax=ax, label=label)
    fig.tight_layout(); fig.savefig(path, dpi=200)
    plt.close(fig)


def figure6(cfg):
    cal = cfg["calibration"]
    imp = cfg["import"]
    subj = cfg["subject"]
    Sd, b, Smax, crf = load_calibration(cal["output_dir"])
    params = {"Sd": Sd, "b": b, "Smax": Smax}

    directory = subj["directory"]
    experiment_title = subj["experiment_title"]
    # Write pipeline output under figure_outputs/ (absolute path) so the tracked
    # data/Images tree isn't polluted with large generated HDR_data files.
    base = str(OUT / f"{experiment_title}_HDR_data")

    results = {}
    for method in ["default", "adaptive"]:
        processed = run_hdr(directory, experiment_title, base,
                            imp["preprocessing_ops"], params, crf,
                            step2.debevec, method=method)
        if not processed:
            raise RuntimeError(f"no QD radiance map produced ({method})")
        results[method] = processed[0]
        rad_log = processed[0]["radiance_map"]
        tag = "HDR" if method == "default" else "HDRstar"
        _save_radiance_png(rad_log, f"Fig 6 — QD {tag} (linear)",
                           OUT / f"fig6_QD_{method}_linear.png", log=False)
        _save_radiance_png(rad_log, f"Fig 6 — QD {tag} (log)",
                           OUT / f"fig6_QD_{method}_log.png", log=True)

    key = results["default"]["key"]

    # --- Single-exposure intensity distributions ---
    stack, exps = load_processed_stack(directory, base, key)
    if stack is not None:
        bins = np.linspace(0, float(np.nanmax(stack)), 200)
        df = pd.DataFrame({"bin_center": 0.5 * (bins[:-1] + bins[1:])})
        for i, t in enumerate(exps):
            _, counts = hist_centers_counts(stack[i].flatten(), bins)
            df[f"t_{t:.3f}s"] = counts
        save_csv(df, "fig6_single_exposure_hist.csv")

        fig, ax = plt.subplots(figsize=(6, 4))
        for i, t in enumerate(exps):
            c, n = hist_centers_counts(stack[i].flatten(), bins)
            ax.plot(c, n, lw=1, label=f"{t:.3f}s")
        ax.set_yscale("log")
        ax.set_xlabel("pixel intensity (DN)"); ax.set_ylabel("count")
        ax.set_title("Fig 6 — single-exposure intensity")
        ax.legend(fontsize=7, ncol=2)
        fig.tight_layout(); fig.savefig(OUT / "fig6_single_exposure_hist.png", dpi=200)
        plt.close(fig)

    # --- HDR vs HDR* radiance distributions (linear radiance x-axis) ---
    # HDR  = default Debevec fusion;  HDR* = adaptive exposure selection.
    def lin_rad(rad_log):
        lin = np.exp(rad_log)
        return lin[np.isfinite(lin) & (lin > 0)]

    hdr = lin_rad(results["default"]["radiance_map"])
    hdrs = lin_rad(results["adaptive"]["radiance_map"])
    hi = max(hdr.max(), hdrs.max())

    # CSV keeps the full radiance range (all data, for Prism).
    bins = np.linspace(0.0, hi, 300)
    c, n_hdr = hist_centers_counts(hdr, bins)
    _, n_hdrs = hist_centers_counts(hdrs, bins)
    save_csv(pd.DataFrame({"radiance_bin": c,
                           "count_HDR": n_hdr, "count_HDRstar": n_hdrs}),
             "fig6_hdr_radiance_hist.csv")

    # X-axis spans the full range from 0, but the lines only begin at radiance
    # 350 so the large background peak near 0 doesn't overwhelm the real signal.
    START_PLOT = 350.0
    vis = c >= START_PLOT
    fig, ax = plt.subplots(figsize=(6, 4))
    ax.plot(c[vis], n_hdr[vis], label="HDR (default)", lw=1.5)
    ax.plot(c[vis], n_hdrs[vis], label="HDR* (adaptive)", lw=1.5)
    ax.set_xlim(0, hi)
    if vis.any():
        ax.set_ylim(0, 1.05 * max(n_hdr[vis].max(), n_hdrs[vis].max()))
    ax.set_xlabel("radiance (a.u.)"); ax.set_ylabel("count")
    ax.set_title("Fig 6 — HDR radiance distribution")
    ax.legend(fontsize=8)
    fig.tight_layout(); fig.savefig(OUT / "fig6_hist_full.png", dpi=200)
    plt.close(fig)


# --------------------------------------------------------------------------- #
#  Figure 7 — not replicated
# --------------------------------------------------------------------------- #
# Figure 7 (ROI line profiles through the mouse) is not regenerated here: it
# requires manually drawn regions of interest and hand-placed line-profile
# coordinates that are not encoded anywhere in the pipeline. Reproduce it by
# loading fig6_QD_*.npy outputs and drawing the ROIs interactively.


# --------------------------------------------------------------------------- #
#  Driver
# --------------------------------------------------------------------------- #

FIGURES = {
    "3":    figure3,
    "4ad":  figure4ad,
    "4ef":  figure4ef,
    "4g":   figure4g,
    "5":    figure5,
    "6":    figure6,
}


def main():
    parser = argparse.ArgumentParser(description="Regenerate manuscript figure data.")
    parser.add_argument("--figure", default=None,
                        help="One of: 3, 4ad, 4ef, 4g, 5, 6 (default: all). "
                             "'--figure 4' runs all of 4ad/4ef/4g.")
    parser.add_argument("--config", default=None, help="Path to config.yaml")
    args = parser.parse_args()

    cfg = load_config(args.config)
    OUT.mkdir(exist_ok=True)

    if args.figure is None:
        todo = list(FIGURES.keys())
    elif args.figure == "4":
        todo = ["4ad", "4ef", "4g"]
    else:
        if args.figure not in FIGURES:
            parser.error(f"unknown figure {args.figure!r}; choose from "
                         f"{list(FIGURES)} or 4")
        todo = [args.figure]

    summary = {}
    for fig_id in todo:
        print("\n" + "=" * 60)
        print(f"  Figure {fig_id}")
        print("=" * 60)
        try:
            FIGURES[fig_id](cfg)
            summary[fig_id] = "OK"
        except Exception as e:
            summary[fig_id] = f"FAILED: {e}"
            traceback.print_exc()

    print("\n" + "=" * 60)
    print("  Summary")
    print("=" * 60)
    for fig_id in todo:
        print(f"  Figure {fig_id:5s} : {summary[fig_id]}")
    print(f"\nOutputs written to {OUT}")
    print("Figure 7 is not replicated (manual ROIs / line profiles).")


if __name__ == "__main__":
    main()
